#!/bin/bash

_vagrant() 
{
    local cur prev opts base
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    #
    #  The basic options we'll complete.
    #
    opts="-v -h box destroy halt help hostmanager init package plugin provision reload resume ssh ssh-config status suspend up"


    #
    #  Complete the arguments to some of the basic commands.
    #
    case "${prev}" in
	ssh|ssh-config|up|destroy|provision|hostmanager|status)
	    local running=$(echo .vagrant/machines/* | sed 's#.vagrant/machines/##g' )
	    COMPREPLY=( $(compgen -W "${running}" -- ${cur}) )
            return 0
            ;;
        *)
        ;;
    esac

   COMPREPLY=($(compgen -W "${opts}" -- ${cur}))  
   return 0
}
complete -F _vagrant vagrant
